### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by talhabadat** [Jcoopt/Robot_Arm#1]
hello Joseph Thomas awesome robot arm developed by you. i need your help to creat robot arm for my college project

**Comment by Jcoopt** [comment]
How can i help?

**Comment by Jcoopt** [comment]
Bear in mind this was a project put together by a much younger me.

**Comment by talhabadat** [comment]
thanks you for your reply , if you don't mind can we discuss about it in private message on twitter.

**Comment by Jcoopt** [comment]
sure. "jthomascoop" is the username

**Comment by talhabadat** [comment]
i am trying to contact you on twitter but you didn't respond there

**Comment by Jcoopt** [comment]
Really? Odd. what's your username and I'll try and find you.

**Comment by talhabadat** [comment]
@talhabadat
